//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "field")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub data: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::item_field::Entity")]
    ItemField,
}

impl Related<super::item_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemField.def()
    }
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        super::item_field::Relation::Items.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::item_field::Relation::Field.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
