//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "items")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub name: Option<String>,
    pub quantity: Option<i32>,
    pub unit: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub instock: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tags::Entity")]
    Tags,
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl Related<super::locations::Entity> for Entity {
    fn to() -> RelationDef {
        super::item_location::Relation::Locations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::item_location::Relation::Items.def().rev())
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::item_group::Relation::Groups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::item_group::Relation::Items.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
