//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub mod prelude;

pub mod group_location;
pub mod groups;
pub mod item_group;
pub mod item_location;
pub mod items;
pub mod locations;
pub mod tags;
pub mod custom;