//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod categories;
pub mod field;
pub mod groups;
pub mod item_field;
pub mod item_group;
pub mod items;
pub mod locations;
pub mod custom;